### PR TITLE
Avoid delete failures

### LINKED ISSUE #128: Do not fail if resource already deleted
If the `delete` command returns a `Not Found` because the resource already doesn't exist then we shouldn't consider it an error. Instead we should accept that the resource has already been deleted.

### PR DESCRIPTION
**Pull request by chesleybrown**
# What

- fixes #128 
- do not error out on trying to delete a resource that already doesn't exist on the server
- adds a warning emit when there is an attempt to delete a resource that doesn't exist

# Testing

- added automated functional tests for deleting non-existent resources and verified the warning

### CODE REVIEW

File: src/lib/kubectl.js [hunk 1]
```diff
@@ -450,8 +450,19 @@ class Kubectl extends EventEmitter {
           `DryRun is enabled: skipping kubectl.delete(${filepath})`
         );
       }
-      this.spawn(["delete", "-f", filepath], function(err, data) {
+      this.spawn(["delete", "-f", filepath], (err, data) => {
         if (err) {
+          if (typeof err === "string" && err.includes("(NotFound)")) {
```
Comment (erutherford) [inline src/lib/kubectl.js]: any concern about this being too generic?

Comment (chesleybrown) [reply src/lib/kubectl.js]: Hm, maybe. Made it more explicit in a614b39.
