### PR TITLE
Auto-retry on kubectl failures

### LINKED ISSUE #127: Auto-retry on failure
Deployments can fail for a number of reasons but often a simple retry will resolve it.

We should have a certain number of automatic retries for the following types of failures:

- kubectl API response errors (such as get, delete, list, apply)
- http network request failures
- timeouts

### PR DESCRIPTION
**Pull request by chesleybrown**
# What

- closes #127 
- Automatically backoff and retry when failing a kubectl or kubeapi request
- Using https://github.com/MathieuTurcotte/node-backoff package
- Enabled linting again and fixed all the lint errors

# Testing

- functional and unit tests on codeship and travis

# TODO

- [x] Add retrying and backoff of `spawn` commands
- [x] Add retrying and backoff of `kubeapi` commands
- [x] Emit `backoff` #event when a retry is done so it can be tracked

### CODE REVIEW

File: src/lib/kubectl.js [hunk 1]
```diff
@@ -225,14 +234,7 @@ class Kubectl extends EventEmitter {
...
 
-  /**
-	 * Spawn is used internally by methods like get and create and it emits a message
-	 * for whenever its called so you can track the number of processes spawned if needed.
-	 * @param {array} args - Array list of the command args
-	 * @param {func} done - Function to call when done
-	 * @fires KubectlWatcher#spawn which tells when spawn is called and with what args
-	 */
-  spawn(args, done) {
+  _spawn(args, done) {
```
Comment (c1freitas) [inline src/lib/kubectl.js]: `_spawn` vs `spawn`?

File: src/lib/kubectl.js [hunk 2]
```diff
@@ -278,115 +280,189 @@ class Kubectl extends EventEmitter {
...
-        name = "";
+  /**
+	 * Spawn is used internally by methods like get and create and it emits a message
+	 * for whenever its called so you can track the number of processes spawned if needed.
+	 * It includes an automatic retry and backoff.
+	 * @param {array} args - Array list of the command args
+	 * @param {func} done - Function to call when done
+	 * @fires KubectlWatcher#spawn which tells when spawn is called and with what args
+	 */
+  spawn(args, done) {
```
Comment (c1freitas) [inline src/lib/kubectl.js]: should this be `_spawn`?

File: Dockerfile [hunk 3]
```diff
@@ -25,6 +25,9 @@ ENV \
 	DIFF=false\
 	FORCE=false\
 	CREATE_ONLY=false\
+	BACKOFF_FAIL_AFTER=10\
```
[the remark this answers is not in the document]
Comment (chesleybrown) [reply Dockerfile]: I will, but this is just the `kit-deployer` lib repo.

File: src/lib/kubectl.js (hunk 1 above)
Comment (chesleybrown) [reply src/lib/kubectl.js]: `spawn` is the public facing method that should be used as it will wrap the spawn request in a backoff. `_spawn` is the function that handles doing the spawn.

File: src/lib/kubectl.js (hunk 2 above)
Comment (chesleybrown) [reply src/lib/kubectl.js]: No, it should be `spawn` because that's the method you should call and it wraps the spawn request in a backoff for you. The `_spawn` is just the internal function of doing the spawn.

File: Dockerfile (hunk 3 above)
[the remark this answers is not in the document]
Comment (c1freitas) [reply Dockerfile]: <doh!>

**Comment by chesleybrown** [comment]
🤣
