### PR TITLE
Fixes #70

### LINKED ISSUE #70: KubectlEventWatcher.emit Unhandled rejection Error
If the health-check encounters an error trying to get the list of `events` from kubectl it is emitting an `error` event but nothing is actually listening on it causing a fatal failure.

```
Unhandled rejection Error: Uncaught, unspecified "error" event. (Unable to connect to the server: net/http: TLS handshake timeout
)
    at KubectlEventWatcher.emit (events.js:166:17)
    at kubectl.get.then.catch (/node_modules/kit-deployer/src/lib/kubectl.js:94:11)
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:555:18)
    at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:600:10)
    at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:679:18)
    at Async._drainQueue (/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues (/node_modules/bluebird/js/release/async.js:16:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

### PR DESCRIPTION
**Pull request by chesleybrown**
If KubectlEventWatcher had an error it emits an error event so we must listen
for it otherwise node throws an unhandled rejection error.

### CODE REVIEW

File: src/lib/health-check.js [hunk 1]
```diff
@@ -36,6 +36,9 @@ class HealthCheck extends EventEmitter {
 	}
 
 	start(name) {
+		this.events.on("error", (err) => {
+			this.emit("error", err);
```
Comment (chesleybrown) [inline src/lib/health-check.js]: And just for further verification, we are already listening for "error" events from the HealthCheck so it's safe to do this.

https://github.com/InVisionApp/kit-deployer/blob/master/src/lib/status.js#L76
